theme: jekyll-theme-cayman
title: Computer Science
description: This is basically just a collection of all of my computer science stuff. Everything here is for people to learn with. - Zachary Lineman
logo: /logo.png
show_downloads: true
google_anylitics: UA-150906839-1
